//Khởi tạo thư viện icon của riêng bạn
import { library } from "@fortawesome/fontawesome-svg-core";
import { faFacebook, faGoogle, faInstagram, faTwitter } from "@fortawesome/free-brands-svg-icons";
import {  faBell, faCalendarAlt, faEnvelope, faEyeSlash, faStarHalfAlt, faTrashAlt  } from "@fortawesome/free-regular-svg-icons";

//Import các icon mà bạn muốn sử dụng trong từng 


import {
  faArrowLeft,
  faBars,
  faBellConcierge,
  faCartShopping,
  faChartLine,
  faChartSimple,
  faChevronDown,
  faChevronUp,
  faDollarSign,
  faExclamationTriangle,
  faEye,
  faFileInvoice,
  faGauge,
  faGift,
  faHeart,
  faIdCard,
  faList,
  faLock,
  faMinus,
  faPlus,
  faRemove,
  faRocket,
  faRotate,
  faSearch,
  faShare,
  faShoppingBag,
  faSignOutAlt,
  faStar,
  faTag,
  faUser,
  faUserCircle,
  faUserCog,
} from "@fortawesome/free-solid-svg-icons";

//Add các icon đã được import vào trong thư viện của bạn
library.add(
    faSearch,
    faUserCircle,
    faChevronUp,
    faChevronDown,
    faShoppingBag,
    faFacebook,
    faGoogle,
    faTwitter,
    faInstagram,
    faEye,
    faHeart,
    faChartSimple,
    faRocket,
    faRotate,
    faTag,
    faLock,
    faStar,
    faShare,
    faStarHalfAlt,
    faGauge,
    faGift,
    faFileInvoice,
    faUser,
    faChartLine,
    faBars,
    faBell,
    faEnvelope,
    faList,
    faBellConcierge,
    faCartShopping,
    faCalendarAlt,
    faEye,
    faEyeSlash,
    faExclamationTriangle,
    faIdCard,
    faSignOutAlt,
    faUserCog,
    faDollarSign,
    faRemove,
    faMinus,
    faTrashAlt,
    faPlus,
    faArrowLeft
);
